---
product_name: IntelliJ Platform SDK
product_version:
product_type: DevGuide

url: https://www.jetbrains.org
baseurl: /intellij/sdk/docs/

description: Documentation for working with and extending the IntelliJ Platform SDK

# 2020.1.1
upsource:
  server: upsource.jetbrains.com
  repo: idea-ce
  commit: 40e5005d02df57f58ac2d498867446c43d61101f
  tag: 201.7223.91

github_repo: JetBrains/intellij-sdk-docs
youtrack_project: IJSDK

exclude:
  - code_samples
